In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [5]:
print(a.dtype,a.shape,a.ndim)

int32 (5,) 1


In [4]:
b = np.array([1.0,2.0,3.0,4.0,5.0])
print(b.dtype,b.shape,b.ndim)

float64 (5,) 1


In [7]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d,d.shape,d.ndim)
print(d[1][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 2
5


In [13]:
print(d[1:,:2])    # [start:end:gap,start:end:gap]

[[4 5 6]
 [7 8 9]]


In [15]:
print(d[1:2,1:])                #[[5,6]]

[[5 6]]


In [17]:
print(d[:,2:])                           #[3,6,9]

[[3]
 [6]
 [9]]


In [18]:
a = np.array([1,2,3,4,5])
print(a[-1])
print(a[1:3])
print(a[::2])        # start:end:gap
print(a[a > 2])

5
[2 3]
[1 3 5]
[3 4 5]


In [21]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a+b)
print(a*b)
print(a**b)
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.log2(a))
print(np.pow(a,2))

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[      1     128    6561  262144 9765625]


In [24]:
score = np.array([45,60,75,95,76,59])
print(np.where(score>60,"Pass","fail"))

['fail' 'fail' 'Pass' 'Pass' 'Pass' 'fail']


In [27]:
temps = np.array([38, 22, 15, 41, 30])
# temp > 37 -> 'fever' , temp <= 20 -> 'cold' , else -> 'normal'
# ['fever','normal','cold','fever','normal']
x = np.array([-3, -1, 0, 2, 5])
# number>0 print -number, number==0 print 0, number<0 print number**2
# [9,1,0,-2,-5]

print(np.where(temps>37,'fever',np.where(temps<=20,'cold','normal')))
print(np.where(x>0,-x,np.where(x==0,0,x**2)))

['fever' 'normal' 'cold' 'fever' 'normal']
[ 9  1  0 -2 -5]
